name: agri
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  animate_do: ^3.3.4
  firebase_auth: ^5.1.2
  http: ^1.2.2
  url_launcher: ^6.3.0
  google_generative_ai: ^0.4.3
  image_picker: ^1.1.2
  flutter_markdown: ^0.7.3
  shared_preferences: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/lang/
    - assets/crop.jpg
    - assets/disease.jpg
    - assets/fertilizer.jpg
    - assets/agricultural_techniques.jpg
    - assets/crop_selection.jpg
    - assets/fertilizers.jpg
    - assets/pesticide_harm.jpg
    - assets/famous farmer.jpg
    - assets/farmer phone.jpg
    - assets/farmerphone.jpg
    - assets/farmerbot.jpg
    - assets/weather.jpg
    - assets/homepage.jpg
